apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-canary
  namespace: lab32
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
      track: canary
  template:
    metadata:
      labels:
        app: demo-api
        track: canary
    spec:
      containers:
      - name: api
        image: amarofuentes10/shared-client:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /ruta-que-no-existe
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 2
