name: Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    uses: amarofuentes10/shared-workflows/.github/workflows/deploy-api.yml@main

    with:
      image-name: shared-client
      image-tag: ${{ github.ref_name }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}